version: "3.7"

services:
  database:
    image: postgres:13
    ports:
      - 5433:5432
    networks:
      - scraper_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dmt_share
    volumes:
      - ./database/_container_startup_ddl/:/docker-entrypoint-initdb.d/
      - ./database/ddl/:/ddl

  scraper:
    image: scraper:1
    networks:
      - scraper_network
    volumes:
      - ./database:/app/database
    depends_on:
      - database

networks:
  scraper_network:
    name: scraper_network
