FROM python:3.9-slim-buster

RUN apt-get update -y && \
    apt-get install -y wget gnupg gnupg2 gnupg1 && \
    apt-get install -y unzip && \
    apt-get install -y cron && \
    apt-get install -y postgresql-client && \
    apt-get install -y gcc musl-dev && \
    apt-get install -y build-essential && \
    apt-get install -y python3-lxml python-dev python3-dev && \
    apt-get install -y libxslt-dev libxml2-dev libffi-dev libssl-dev && \
    apt-get install -y curl && \
    apt-get install -y chromium

########## Setup Selenium with Google Chrome ##########
ENV CHROMEDRIVER_DIR /chromedriver
RUN mkdir $CHROMEDRIVER_DIR
ENV PATH $CHROMEDRIVER_DIR:$PATH

RUN wget https://github.com/electron/electron/releases/download/v12.0.9/chromedriver-v12.0.9-linux-armv7l.zip
RUN unzip chromedriver-v12.0.9-linux-armv7l.zip -d /usr/local/bin/
RUN rm chromedriver-v12.0.9-linux-armv7l.zip

########## Setup Scraper Project ##########
ENV TZ Asia/Jakarta
ENV SCRAPER_PROJECT_DIR /app/web_scraping
ENV SCRAPER_RESULT_DIR /app/web_scraping/result
ENV SCRAPER_BACKUP_DIR /backup
ENV SCRAPER_DATABASE_HOST database

WORKDIR /app/web_scraping
COPY scraper scraper/
COPY loader loader/
COPY job_web_scraping.sh .
COPY requirements.txt .
COPY schedule.txt .
RUN find . -type d -name '__pycache__' -exec rm -r {} \; -prune

RUN mkdir /logs/
RUN mkdir /backup/

RUN pip install -r requirements.txt
COPY schedule.txt /etc/cron.d/schedule.txt
RUN chmod 0644 /etc/cron.d/schedule.txt
RUN crontab /etc/cron.d/schedule.txt

########## Keep Container Running ##########
CMD ["cron", "&&", "tail", "-f", "/dev/null"]
