SET client_min_messages TO WARNING;

DROP SCHEMA IF EXISTS cdc;
CREATE SCHEMA cdc;

DROP SCHEMA IF EXISTS tmp;
CREATE SCHEMA tmp;

DROP SCHEMA IF EXISTS log;
CREATE SCHEMA log;

DROP SCHEMA IF EXISTS ws;
CREATE SCHEMA ws;
