runtime: python37
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: B4
basic_scaling:
  max_instances: 4
  idle_timeout: 10m
handle:
- url: /data
  http_headers:
    Access-Control-Allow-Origin: *
- url: /classify
  http_headers:
    Access-Control-Allow-Origin: *
